### PR TITLE
Add cmd PkgREPL command

### PR DESCRIPTION
**Pull request by frankier**
This is useful because the `run` PkgREPL command was picking up my system `mamba` even though MicroMamba was in use. This is some type of a PATH issue probably, but at any rate, this approach which will reliably target the correct executable seems like a useful addition since it can be more robust.

### CODE REVIEW

**Comment by cjdoris** [comment]
This is so similar to `conda run` that maybe they should be merged? That is, change `conda run` so that if the first arg is `conda` (or `mamba` or `micromamba`?) then run whatever CondaPkg runs?

**Comment by frankier** [comment]
That makes sense. So to confirm the plan would be:

 * Do the same as `conda cmd` procedure when any of these match
 * Don't do it when they are quoted
 * Document this in the docstring of `conda run`

I'll modify this PR with these changes soonish

**Comment by frankier** [comment]
Done

**Comment by cjdoris** [comment]
Thanks for the PR - I came to review it and had some comments, but in the end decided it would be quickest to just implement my ideas directly. I went with a simpler version, which just checks if the first arg is "conda" regardless of quoting. I didn't think the extra complexity was worth it for what is really just a convenience function. It's released now.

**Pull request closed without merging**
